import { randomBytes } from "node:crypto";

/**
 * Triply-issued confirmation numbers for DIRECT-lot bookings (plan D3). They
 * live in the same `bookings.reslab_reservation_number` column as ResLab's
 * `RTL…` numbers so every existing lookup (confirmation page, QR, emails,
 * admin, cancel) keeps working. The prefix makes the two sources
 * distinguishable at a glance and in SQL.
 *
 * Format: TRP- + 8 chars of Crockford base32 (no I, L, O, U — unambiguous when
 * read over the phone at a lot gate). 32^8 ≈ 1.1e12 values; collisions are
 * caught by the partial UNIQUE index on pending_bookings (migration 034) and
 * regenerated by the caller.
 */
const ALPHABET = "0123456789ABCDEFGHJKMNPQRSTVWXYZ";
export const TRIPLY_CONFIRMATION_RE = /^TRP-[0-9A-HJKMNP-TV-Z]{8}$/;
export const RESLAB_CONFIRMATION_RE = /^RTL\d+$/;

export function issueConfirmationNumber(bytes: (n: number) => Uint8Array = (n) => randomBytes(n)): string {
  const raw = bytes(8);
  let out = "";
  for (let i = 0; i < 8; i++) out += ALPHABET[raw[i] % 32];
  return `TRP-${out}`;
}

export const isTriplyConfirmationNumber = (value: string): boolean => TRIPLY_CONFIRMATION_RE.test(value);
export const isReslabConfirmationNumber = (value: string): boolean => RESLAB_CONFIRMATION_RE.test(value);
