export interface Airport {
  code: string;
  name: string;
  city: string;
  state: string;
  country?: string;
  timezone: string;
  latitude: number;
  longitude: number;
  slug: string;
  enabled: boolean;
  isTest?: boolean; // Flag for test locations
  reslabLocationId?: number; // Direct mapping to ResLab location ID
}

export const airports: Airport[] = [
  // ==========================================================================
  // Production Airports (85 locations from ResLab inventory)
  // ==========================================================================
  {
    code: "ABE",
    name: "Lehigh Valley International Airport",
    city: "Allentown",
    state: "PA",
    timezone: "America/New_York",
    latitude: 40.6521,
    longitude: -75.4408,
    slug: "allentown-abe",
    enabled: true,
  },
  {
    code: "ABQ",
    name: "Albuquerque International Sunport",
    city: "Albuquerque",
    state: "NM",
    timezone: "America/Denver",
    latitude: 35.0402,
    longitude: -106.6092,
    slug: "albuquerque-abq",
    enabled: true,
  },
  {
    code: "ALB",
    name: "Albany International Airport",
    city: "Albany",
    state: "NY",
    timezone: "America/New_York",
    latitude: 42.7483,
    longitude: -73.8017,
    slug: "albany-alb",
    enabled: true,
  },
  {
    code: "ATL",
    name: "Hartsfield-Jackson Atlanta International Airport",
    city: "Atlanta",
    state: "GA",
    timezone: "America/New_York",
    latitude: 33.6407,
    longitude: -84.4277,
    slug: "atlanta-atl",
    enabled: true,
  },
  {
    code: "AUS",
    name: "Austin-Bergstrom International Airport",
    city: "Austin",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 30.1975,
    longitude: -97.6664,
    slug: "austin-aus",
    enabled: true,
  },
  {
    code: "AZO",
    name: "Kalamazoo/Battle Creek International Airport",
    city: "Kalamazoo",
    state: "MI",
    timezone: "America/New_York",
    latitude: 42.2350,
    longitude: -85.5521,
    slug: "kalamazoo-azo",
    enabled: true,
  },
  {
    code: "BDL",
    name: "Bradley International Airport",
    city: "Hartford",
    state: "CT",
    timezone: "America/New_York",
    latitude: 41.9389,
    longitude: -72.6832,
    slug: "hartford-bdl",
    enabled: true,
  },
  {
    code: "BHM",
    name: "Birmingham-Shuttlesworth International Airport",
    city: "Birmingham",
    state: "AL",
    timezone: "America/Chicago",
    latitude: 33.5629,
    longitude: -86.7535,
    slug: "birmingham-bhm",
    enabled: true,
  },
  {
    code: "BNA",
    name: "Nashville International Airport",
    city: "Nashville",
    state: "TN",
    timezone: "America/Chicago",
    latitude: 36.1263,
    longitude: -86.6774,
    slug: "nashville-bna",
    enabled: true,
  },
  {
    code: "BOS",
    name: "Boston Logan International Airport",
    city: "Boston",
    state: "MA",
    timezone: "America/New_York",
    latitude: 42.3656,
    longitude: -71.0096,
    slug: "boston-bos",
    enabled: true,
  },
  {
    code: "BUF",
    name: "Buffalo Niagara International Airport",
    city: "Buffalo",
    state: "NY",
    timezone: "America/New_York",
    latitude: 42.9405,
    longitude: -78.7322,
    slug: "buffalo-buf",
    enabled: true,
  },
  {
    code: "BUR",
    name: "Hollywood Burbank Airport",
    city: "Burbank",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 34.2007,
    longitude: -118.3585,
    slug: "burbank-bur",
    enabled: true,
  },
  {
    code: "BWI",
    name: "Baltimore/Washington International Airport",
    city: "Baltimore",
    state: "MD",
    timezone: "America/New_York",
    latitude: 39.1754,
    longitude: -76.6684,
    slug: "baltimore-bwi",
    enabled: true,
  },
  {
    code: "CHS",
    name: "Charleston International Airport",
    city: "Charleston",
    state: "SC",
    timezone: "America/New_York",
    latitude: 32.8986,
    longitude: -80.0405,
    slug: "charleston-chs",
    enabled: true,
  },
  {
    code: "CLE",
    name: "Cleveland Hopkins International Airport",
    city: "Cleveland",
    state: "OH",
    timezone: "America/New_York",
    latitude: 41.4117,
    longitude: -81.8498,
    slug: "cleveland-cle",
    enabled: true,
  },
  {
    code: "CLT",
    name: "Charlotte Douglas International Airport",
    city: "Charlotte",
    state: "NC",
    timezone: "America/New_York",
    latitude: 35.2140,
    longitude: -80.9431,
    slug: "charlotte-clt",
    enabled: true,
  },
  {
    code: "CVG",
    name: "Cincinnati/Northern Kentucky International Airport",
    city: "Cincinnati",
    state: "KY",
    timezone: "America/New_York",
    latitude: 39.0488,
    longitude: -84.6678,
    slug: "cincinnati-cvg",
    enabled: true,
  },
  {
    code: "DAL",
    name: "Dallas Love Field",
    city: "Dallas",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 32.8471,
    longitude: -96.8518,
    slug: "dallas-dal",
    enabled: true,
  },
  {
    code: "DCA",
    name: "Ronald Reagan Washington National Airport",
    city: "Washington",
    state: "VA",
    timezone: "America/New_York",
    latitude: 38.8512,
    longitude: -77.0402,
    slug: "washington-dca",
    enabled: true,
  },
  {
    code: "DEN",
    name: "Denver International Airport",
    city: "Denver",
    state: "CO",
    timezone: "America/Denver",
    latitude: 39.8561,
    longitude: -104.6737,
    slug: "denver-den",
    enabled: true,
  },
  {
    code: "DFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 32.8998,
    longitude: -97.0403,
    slug: "dallas-dfw",
    enabled: true,
  },
  {
    code: "DSM",
    name: "Des Moines International Airport",
    city: "Des Moines",
    state: "IA",
    timezone: "America/Chicago",
    latitude: 41.5340,
    longitude: -93.6631,
    slug: "des-moines-dsm",
    enabled: true,
  },
  {
    code: "DTW",
    name: "Detroit Metropolitan Wayne County Airport",
    city: "Detroit",
    state: "MI",
    timezone: "America/New_York",
    latitude: 42.2124,
    longitude: -83.3534,
    slug: "detroit-dtw",
    enabled: true,
  },
  {
    code: "ELP",
    name: "El Paso International Airport",
    city: "El Paso",
    state: "TX",
    timezone: "America/Denver",
    latitude: 31.8072,
    longitude: -106.3778,
    slug: "el-paso-elp",
    enabled: true,
  },
  {
    code: "EWR",
    name: "Newark Liberty International Airport",
    city: "New York",
    state: "NJ",
    timezone: "America/New_York",
    latitude: 40.6895,
    longitude: -74.1745,
    slug: "new-york-ewr",
    enabled: true,
  },
  {
    code: "FAT",
    name: "Fresno Yosemite International Airport",
    city: "Fresno",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 36.7762,
    longitude: -119.7181,
    slug: "fresno-fat",
    enabled: true,
  },
  {
    code: "FLL",
    name: "Fort Lauderdale-Hollywood International Airport",
    city: "Fort Lauderdale",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.0742,
    longitude: -80.1506,
    slug: "fort-lauderdale-fll",
    enabled: true,
  },
  {
    code: "GEG",
    name: "Spokane International Airport",
    city: "Spokane",
    state: "WA",
    timezone: "America/Los_Angeles",
    latitude: 47.6199,
    longitude: -117.5338,
    slug: "spokane-geg",
    enabled: true,
  },
  {
    code: "GSO",
    name: "Piedmont Triad International Airport",
    city: "Greensboro",
    state: "NC",
    timezone: "America/New_York",
    latitude: 36.0978,
    longitude: -79.9373,
    slug: "greensboro-gso",
    enabled: true,
  },
  {
    code: "HOU",
    name: "William P. Hobby Airport",
    city: "Houston",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 29.6454,
    longitude: -95.2789,
    slug: "houston-hou",
    enabled: true,
  },
  {
    code: "HPN",
    name: "Westchester County Airport",
    city: "White Plains",
    state: "NY",
    timezone: "America/New_York",
    latitude: 41.0670,
    longitude: -73.7076,
    slug: "white-plains-hpn",
    enabled: true,
  },
  {
    code: "IAD",
    name: "Washington Dulles International Airport",
    city: "Washington",
    state: "VA",
    timezone: "America/New_York",
    latitude: 38.9531,
    longitude: -77.4565,
    slug: "washington-iad",
    enabled: true,
  },
  {
    code: "IAH",
    name: "George Bush Intercontinental Airport",
    city: "Houston",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 29.9902,
    longitude: -95.3368,
    slug: "houston-iah",
    enabled: true,
  },
  {
    code: "IDA",
    name: "Idaho Falls Regional Airport",
    city: "Idaho Falls",
    state: "ID",
    timezone: "America/Boise",
    latitude: 43.5146,
    longitude: -112.0708,
    slug: "idaho-falls-ida",
    enabled: true,
  },
  {
    code: "IND",
    name: "Indianapolis International Airport",
    city: "Indianapolis",
    state: "IN",
    timezone: "America/Indiana/Indianapolis",
    latitude: 39.7173,
    longitude: -86.2944,
    slug: "indianapolis-ind",
    enabled: true,
  },
  {
    code: "JAX",
    name: "Jacksonville International Airport",
    city: "Jacksonville",
    state: "FL",
    timezone: "America/New_York",
    latitude: 30.4941,
    longitude: -81.6879,
    slug: "jacksonville-jax",
    enabled: true,
  },
  {
    code: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    latitude: 40.6413,
    longitude: -73.7781,
    slug: "new-york-jfk",
    enabled: true,
  },
  {
    code: "LAS",
    name: "Harry Reid International Airport",
    city: "Las Vegas",
    state: "NV",
    timezone: "America/Los_Angeles",
    latitude: 36.0840,
    longitude: -115.1537,
    slug: "las-vegas-las",
    enabled: true,
  },
  {
    code: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 33.9425,
    longitude: -118.4081,
    slug: "los-angeles-lax",
    enabled: true,
  },
  {
    code: "LGA",
    name: "LaGuardia Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    latitude: 40.7769,
    longitude: -73.8740,
    slug: "new-york-lga",
    enabled: true,
  },
  {
    code: "LIT",
    name: "Bill and Hillary Clinton National Airport",
    city: "Little Rock",
    state: "AR",
    timezone: "America/Chicago",
    latitude: 34.7294,
    longitude: -92.2243,
    slug: "little-rock-lit",
    enabled: true,
  },
  {
    code: "MCI",
    name: "Kansas City International Airport",
    city: "Kansas City",
    state: "MO",
    timezone: "America/Chicago",
    latitude: 39.2976,
    longitude: -94.7139,
    slug: "kansas-city-mci",
    enabled: true,
  },
  {
    code: "MCO",
    name: "Orlando International Airport",
    city: "Orlando",
    state: "FL",
    timezone: "America/New_York",
    latitude: 28.4312,
    longitude: -81.3081,
    slug: "orlando-mco",
    enabled: true,
  },
  {
    code: "MDW",
    name: "Chicago Midway International Airport",
    city: "Chicago",
    state: "IL",
    timezone: "America/Chicago",
    latitude: 41.7868,
    longitude: -87.7522,
    slug: "chicago-mdw",
    enabled: true,
  },
  {
    code: "MEM",
    name: "Memphis International Airport",
    city: "Memphis",
    state: "TN",
    timezone: "America/Chicago",
    latitude: 35.0424,
    longitude: -89.9767,
    slug: "memphis-mem",
    enabled: true,
  },
  {
    code: "MIA",
    name: "Miami International Airport",
    city: "Miami",
    state: "FL",
    timezone: "America/New_York",
    latitude: 25.7959,
    longitude: -80.2870,
    slug: "miami-mia",
    enabled: true,
  },
  {
    code: "MKE",
    name: "Milwaukee Mitchell International Airport",
    city: "Milwaukee",
    state: "WI",
    timezone: "America/Chicago",
    latitude: 42.9472,
    longitude: -87.8966,
    slug: "milwaukee-mke",
    enabled: true,
  },
  {
    code: "MLB",
    name: "Orlando Melbourne International Airport",
    city: "Melbourne",
    state: "FL",
    timezone: "America/New_York",
    latitude: 28.1028,
    longitude: -80.6453,
    slug: "melbourne-mlb",
    enabled: true,
  },
  {
    code: "MSP",
    name: "Minneapolis-Saint Paul International Airport",
    city: "Minneapolis",
    state: "MN",
    timezone: "America/Chicago",
    latitude: 44.8848,
    longitude: -93.2223,
    slug: "minneapolis-msp",
    enabled: true,
  },
  {
    code: "MSY",
    name: "Louis Armstrong New Orleans International Airport",
    city: "New Orleans",
    state: "LA",
    timezone: "America/Chicago",
    latitude: 29.9934,
    longitude: -90.2580,
    slug: "new-orleans-msy",
    enabled: true,
  },
  {
    code: "OAK",
    name: "Oakland International Airport",
    city: "Oakland",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 37.7213,
    longitude: -122.2208,
    slug: "oakland-oak",
    enabled: true,
  },
  {
    code: "OKC",
    name: "Will Rogers World Airport",
    city: "Oklahoma City",
    state: "OK",
    timezone: "America/Chicago",
    latitude: 35.3931,
    longitude: -97.6007,
    slug: "oklahoma-city-okc",
    enabled: true,
  },
  {
    code: "ORD",
    name: "O'Hare International Airport",
    city: "Chicago",
    state: "IL",
    timezone: "America/Chicago",
    latitude: 41.9742,
    longitude: -87.9073,
    slug: "chicago-ord",
    enabled: true,
  },
  {
    code: "ORF",
    name: "Norfolk International Airport",
    city: "Norfolk",
    state: "VA",
    timezone: "America/New_York",
    latitude: 36.8946,
    longitude: -76.2012,
    slug: "norfolk-orf",
    enabled: true,
  },
  {
    code: "PBI",
    name: "Palm Beach International Airport",
    city: "West Palm Beach",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.6832,
    longitude: -80.0956,
    slug: "west-palm-beach-pbi",
    enabled: true,
  },
  {
    code: "PDX",
    name: "Portland International Airport",
    city: "Portland",
    state: "OR",
    timezone: "America/Los_Angeles",
    latitude: 45.5898,
    longitude: -122.5951,
    slug: "portland-pdx",
    enabled: true,
  },
  {
    code: "PHL",
    name: "Philadelphia International Airport",
    city: "Philadelphia",
    state: "PA",
    timezone: "America/New_York",
    latitude: 39.8744,
    longitude: -75.2424,
    slug: "philadelphia-phl",
    enabled: true,
  },
  {
    code: "PHX",
    name: "Phoenix Sky Harbor International Airport",
    city: "Phoenix",
    state: "AZ",
    timezone: "America/Phoenix",
    latitude: 33.4373,
    longitude: -112.0078,
    slug: "phoenix-phx",
    enabled: true,
  },
  {
    code: "PIT",
    name: "Pittsburgh International Airport",
    city: "Pittsburgh",
    state: "PA",
    timezone: "America/New_York",
    latitude: 40.4915,
    longitude: -80.2329,
    slug: "pittsburgh-pit",
    enabled: true,
  },
  {
    code: "POE",
    name: "Port Everglades Cruise Port",
    city: "Fort Lauderdale",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.0934,
    longitude: -80.1129,
    slug: "fort-lauderdale-poe",
    enabled: true,
  },
  {
    code: "PVD",
    name: "T.F. Green International Airport",
    city: "Providence",
    state: "RI",
    timezone: "America/New_York",
    latitude: 41.7248,
    longitude: -71.4282,
    slug: "providence-pvd",
    enabled: true,
  },
  {
    code: "RDU",
    name: "Raleigh-Durham International Airport",
    city: "Raleigh",
    state: "NC",
    timezone: "America/New_York",
    latitude: 35.8776,
    longitude: -78.7875,
    slug: "raleigh-rdu",
    enabled: true,
  },
  {
    code: "RIC",
    name: "Richmond International Airport",
    city: "Richmond",
    state: "VA",
    timezone: "America/New_York",
    latitude: 37.5052,
    longitude: -77.3197,
    slug: "richmond-ric",
    enabled: true,
  },
  {
    code: "RNO",
    name: "Reno-Tahoe International Airport",
    city: "Reno",
    state: "NV",
    timezone: "America/Los_Angeles",
    latitude: 39.4991,
    longitude: -119.7681,
    slug: "reno-rno",
    enabled: true,
  },
  {
    code: "ROA",
    name: "Roanoke-Blacksburg Regional Airport",
    city: "Roanoke",
    state: "VA",
    timezone: "America/New_York",
    latitude: 37.3255,
    longitude: -79.9754,
    slug: "roanoke-roa",
    enabled: true,
  },
  {
    code: "ROC",
    name: "Greater Rochester International Airport",
    city: "Rochester",
    state: "NY",
    timezone: "America/New_York",
    latitude: 43.1189,
    longitude: -77.6724,
    slug: "rochester-roc",
    enabled: true,
  },
  {
    code: "RSW",
    name: "Southwest Florida International Airport",
    city: "Fort Myers",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.5362,
    longitude: -81.7552,
    slug: "fort-myers-rsw",
    enabled: true,
  },
  {
    code: "SAN",
    name: "San Diego International Airport",
    city: "San Diego",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 32.7338,
    longitude: -117.1933,
    slug: "san-diego-san",
    enabled: true,
  },
  {
    code: "SAT",
    name: "San Antonio International Airport",
    city: "San Antonio",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 29.5337,
    longitude: -98.4698,
    slug: "san-antonio-sat",
    enabled: true,
  },
  {
    code: "SAV",
    name: "Savannah/Hilton Head International Airport",
    city: "Savannah",
    state: "GA",
    timezone: "America/New_York",
    latitude: 32.1276,
    longitude: -81.2021,
    slug: "savannah-sav",
    enabled: true,
  },
  {
    code: "SDF",
    name: "Louisville Muhammad Ali International Airport",
    city: "Louisville",
    state: "KY",
    timezone: "America/New_York",
    latitude: 38.1744,
    longitude: -85.7360,
    slug: "louisville-sdf",
    enabled: true,
  },
  {
    code: "SEA",
    name: "Seattle-Tacoma International Airport",
    city: "Seattle",
    state: "WA",
    timezone: "America/Los_Angeles",
    latitude: 47.4502,
    longitude: -122.3088,
    slug: "seattle-sea",
    enabled: true,
  },
  {
    code: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 37.6213,
    longitude: -122.3790,
    slug: "san-francisco-sfo",
    enabled: true,
  },
  {
    code: "SJC",
    name: "San Jose Mineta International Airport",
    city: "San Jose",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 37.3626,
    longitude: -121.9290,
    slug: "san-jose-sjc",
    enabled: true,
  },
  {
    code: "SLC",
    name: "Salt Lake City International Airport",
    city: "Salt Lake City",
    state: "UT",
    timezone: "America/Denver",
    latitude: 40.7884,
    longitude: -111.9778,
    slug: "salt-lake-city-slc",
    enabled: true,
  },
  {
    code: "SNA",
    name: "John Wayne Airport",
    city: "Santa Ana",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 33.6757,
    longitude: -117.8678,
    slug: "santa-ana-sna",
    enabled: true,
  },
  {
    code: "STL",
    name: "St. Louis Lambert International Airport",
    city: "St. Louis",
    state: "MO",
    timezone: "America/Chicago",
    latitude: 38.7487,
    longitude: -90.3700,
    slug: "st-louis-stl",
    enabled: true,
  },
  {
    code: "SYR",
    name: "Syracuse Hancock International Airport",
    city: "Syracuse",
    state: "NY",
    timezone: "America/New_York",
    latitude: 43.1112,
    longitude: -76.1063,
    slug: "syracuse-syr",
    enabled: true,
  },
  {
    code: "TPA",
    name: "Tampa International Airport",
    city: "Tampa",
    state: "FL",
    timezone: "America/New_York",
    latitude: 27.9755,
    longitude: -82.5332,
    slug: "tampa-tpa",
    enabled: true,
  },
  {
    code: "TUS",
    name: "Tucson International Airport",
    city: "Tucson",
    state: "AZ",
    timezone: "America/Phoenix",
    latitude: 32.1161,
    longitude: -110.9410,
    slug: "tucson-tus",
    enabled: true,
  },
  {
    code: "TYS",
    name: "McGhee Tyson Airport",
    city: "Knoxville",
    state: "TN",
    timezone: "America/New_York",
    latitude: 35.8110,
    longitude: -83.9940,
    slug: "knoxville-tys",
    enabled: true,
  },
  {
    code: "YOW",
    name: "Ottawa Macdonald-Cartier International Airport",
    city: "Ottawa",
    state: "ON",
    country: "Canada",
    timezone: "America/Toronto",
    latitude: 45.3225,
    longitude: -75.6692,
    slug: "ottawa-yow",
    enabled: true,
  },
  {
    code: "YUL",
    name: "Montreal-Pierre Elliott Trudeau International Airport",
    city: "Montreal",
    state: "QC",
    country: "Canada",
    timezone: "America/Toronto",
    latitude: 45.4706,
    longitude: -73.7408,
    slug: "montreal-yul",
    enabled: true,
  },
  {
    code: "YYC",
    name: "Calgary International Airport",
    city: "Calgary",
    state: "AB",
    country: "Canada",
    timezone: "America/Edmonton",
    latitude: 51.1215,
    longitude: -114.0133,
    slug: "calgary-yyc",
    enabled: true,
  },
  {
    code: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    state: "ON",
    country: "Canada",
    timezone: "America/Toronto",
    latitude: 43.6777,
    longitude: -79.6248,
    slug: "toronto-yyz",
    enabled: true,
  },

  // ==========================================================================
  // Test Locations (ResLab Sandbox) — DISABLED for production
  // ==========================================================================
  {
    code: "TEST-NY",
    name: "Beacon Test Airport (TEST)",
    city: "Beacon",
    state: "NY",
    timezone: "America/New_York",
    latitude: 41.5048158,
    longitude: -73.9695832,
    slug: "beacon-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 195,
  },
  {
    code: "TEST-OH",
    name: "Cincinnati Test Airport (TEST)",
    city: "Cincinnati",
    state: "OH",
    timezone: "America/New_York",
    latitude: 39.1031182,
    longitude: -84.5120196,
    slug: "cincinnati-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 194,
  },
  {
    code: "TEST-CA",
    name: "Albany CA Test Airport (TEST)",
    city: "Albany",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 35.125801,
    longitude: -117.9859038,
    slug: "albany-ca-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 197,
  },
  {
    code: "TEST-QC",
    name: "Montreal Test Airport (TEST)",
    city: "Montreal",
    state: "QC",
    country: "Canada",
    timezone: "America/New_York",
    latitude: 45.5016889,
    longitude: -73.567256,
    slug: "montreal-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 196,
  },
];

export const airportsByCode = airports.reduce(
  (acc, airport) => {
    acc[airport.code] = airport;
    return acc;
  },
  {} as Record<string, Airport>
);

export const airportsBySlug = airports.reduce(
  (acc, airport) => {
    acc[airport.slug] = airport;
    return acc;
  },
  {} as Record<string, Airport>
);

export const enabledAirports = airports.filter((a) => a.enabled);

// Production airports only (excludes test locations)
export const productionAirports = airports.filter(
  (a) => a.enabled && !a.isTest
);

// Test airports only
export const testAirports = airports.filter((a) => a.enabled && a.isTest);

export function getAirportByCode(code: string): Airport | undefined {
  return airportsByCode[code.toUpperCase()];
}

export function getAirportBySlug(slug: string): Airport | undefined {
  return airportsBySlug[slug.toLowerCase()];
}

export function getAirportByReslabLocationId(
  locationId: number
): Airport | undefined {
  return airports.find((a) => a.reslabLocationId === locationId);
}
