export interface Airport {
  code: string;
  name: string;
  city: string;
  state: string;
  country?: string;
  timezone: string;
  latitude: number;
  longitude: number;
  slug: string;
  enabled: boolean;
  isTest?: boolean; // Flag for test locations
  reslabLocationId?: number; // Direct mapping to ResLab location ID
}

export const airports: Airport[] = [
  // ==========================================================================
  // Production Airports (85 locations from ResLab inventory)
  // ==========================================================================
  {
    code: "ABE",
    name: "Lehigh Valley International Airport",
    city: "Allentown",
    state: "PA",
    timezone: "America/New_York",
    latitude: 40.6393613,
    longitude: -75.4320722,
    slug: "allentown-abe",
    enabled: true,
  },
  {
    code: "ABQ",
    name: "Albuquerque International Sunport",
    city: "Albuquerque",
    state: "NM",
    timezone: "America/Denver",
    latitude: 35.0610403,
    longitude: -106.6210476,
    slug: "albuquerque-abq",
    enabled: true,
  },
  {
    code: "ALB",
    name: "Albany International Airport",
    city: "Albany",
    state: "NY",
    timezone: "America/New_York",
    latitude: 42.7246843,
    longitude: -73.7954544,
    slug: "albany-alb",
    enabled: true,
  },
  {
    code: "ATL",
    name: "Hartsfield-Jackson Atlanta International Airport",
    city: "Atlanta",
    state: "GA",
    timezone: "America/New_York",
    latitude: 33.6535411,
    longitude: -84.4924133,
    slug: "atlanta-atl",
    enabled: true,
  },
  {
    code: "AUS",
    name: "Austin-Bergstrom International Airport",
    city: "Austin",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 30.2164705,
    longitude: -97.6936044,
    slug: "austin-aus",
    enabled: true,
  },
  {
    code: "AZO",
    name: "Kalamazoo/Battle Creek International Airport",
    city: "Kalamazoo",
    state: "MI",
    timezone: "America/New_York",
    latitude: 42.2583306,
    longitude: -85.5349093,
    slug: "kalamazoo-azo",
    enabled: true,
  },
  {
    code: "BDL",
    name: "Bradley International Airport",
    city: "Hartford",
    state: "CT",
    timezone: "America/New_York",
    latitude: 41.9269991,
    longitude: -72.6670783,
    slug: "hartford-bdl",
    enabled: true,
  },
  {
    code: "BHM",
    name: "Birmingham-Shuttlesworth International Airport",
    city: "Birmingham",
    state: "AL",
    timezone: "America/Chicago",
    latitude: 33.5493108,
    longitude: -86.7615283,
    slug: "birmingham-bhm",
    enabled: true,
  },
  {
    code: "BNA",
    name: "Nashville International Airport",
    city: "Nashville",
    state: "TN",
    timezone: "America/Chicago",
    latitude: 36.1439853,
    longitude: -86.6648074,
    slug: "nashville-bna",
    enabled: true,
  },
  {
    code: "BOS",
    name: "Boston Logan International Airport",
    city: "Boston",
    state: "MA",
    timezone: "America/New_York",
    latitude: 42.4013299,
    longitude: -71.0062657,
    slug: "boston-bos",
    enabled: true,
  },
  {
    code: "BUF",
    name: "Buffalo Niagara International Airport",
    city: "Buffalo",
    state: "NY",
    timezone: "America/New_York",
    latitude: 42.9527666,
    longitude: -78.6944654,
    slug: "buffalo-buf",
    enabled: true,
  },
  {
    code: "BUR",
    name: "Hollywood Burbank Airport",
    city: "Burbank",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 34.1942269,
    longitude: -118.3590934,
    slug: "burbank-bur",
    enabled: true,
  },
  {
    code: "BWI",
    name: "Baltimore/Washington International Airport",
    city: "Baltimore",
    state: "MD",
    timezone: "America/New_York",
    latitude: 39.2053762,
    longitude: -76.6930183,
    slug: "baltimore-bwi",
    enabled: true,
  },
  {
    code: "CHS",
    name: "Charleston International Airport",
    city: "Charleston",
    state: "SC",
    timezone: "America/New_York",
    latitude: 32.8664431,
    longitude: -80.0196158,
    slug: "charleston-chs",
    enabled: true,
  },
  {
    code: "CLE",
    name: "Cleveland Hopkins International Airport",
    city: "Cleveland",
    state: "OH",
    timezone: "America/New_York",
    latitude: 41.4396989,
    longitude: -81.8057334,
    slug: "cleveland-cle",
    enabled: true,
  },
  {
    code: "CLT",
    name: "Charlotte Douglas International Airport",
    city: "Charlotte",
    state: "NC",
    timezone: "America/New_York",
    latitude: 35.237051,
    longitude: -80.918193,
    slug: "charlotte-clt",
    enabled: true,
  },
  {
    code: "CVG",
    name: "Cincinnati/Northern Kentucky International Airport",
    city: "Cincinnati",
    state: "KY",
    timezone: "America/New_York",
    latitude: 39.0135672,
    longitude: -84.6328714,
    slug: "cincinnati-cvg",
    enabled: true,
  },
  {
    code: "DAL",
    name: "Dallas Love Field",
    city: "Dallas",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 32.8365672,
    longitude: -96.8764384,
    slug: "dallas-dal",
    enabled: true,
  },
  {
    code: "DCA",
    name: "Ronald Reagan Washington National Airport",
    city: "Washington",
    state: "VA",
    timezone: "America/New_York",
    latitude: 38.8571563,
    longitude: -77.0525786,
    slug: "washington-dca",
    enabled: true,
  },
  {
    code: "DEN",
    name: "Denver International Airport",
    city: "Denver",
    state: "CO",
    timezone: "America/Denver",
    latitude: 39.8192165,
    longitude: -104.691081,
    slug: "denver-den",
    enabled: true,
  },
  {
    code: "DFW",
    name: "Dallas/Fort Worth International Airport",
    city: "Dallas",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 32.9173531,
    longitude: -97.0093078,
    slug: "dallas-dfw",
    enabled: true,
  },
  {
    code: "DSM",
    name: "Des Moines International Airport",
    city: "Des Moines",
    state: "IA",
    timezone: "America/Chicago",
    latitude: 41.5303025,
    longitude: -93.644715,
    slug: "des-moines-dsm",
    enabled: true,
  },
  {
    code: "DTW",
    name: "Detroit Metropolitan Wayne County Airport",
    city: "Detroit",
    state: "MI",
    timezone: "America/New_York",
    latitude: 42.2213159,
    longitude: -83.491814,
    slug: "detroit-dtw",
    enabled: true,
  },
  {
    code: "ELP",
    name: "El Paso International Airport",
    city: "El Paso",
    state: "TX",
    timezone: "America/Denver",
    latitude: 31.7809617,
    longitude: -106.3958238,
    slug: "el-paso-elp",
    enabled: true,
  },
  {
    code: "EWR",
    name: "Newark Liberty International Airport",
    city: "New York",
    state: "NJ",
    timezone: "America/New_York",
    latitude: 40.7094686,
    longitude: -74.1727594,
    slug: "new-york-ewr",
    enabled: true,
  },
  {
    code: "FAT",
    name: "Fresno Yosemite International Airport",
    city: "Fresno",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 36.7706666,
    longitude: -119.7242342,
    slug: "fresno-fat",
    enabled: true,
  },
  {
    code: "FLL",
    name: "Fort Lauderdale-Hollywood International Airport",
    city: "Fort Lauderdale",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.0302244,
    longitude: -80.2074466,
    slug: "fort-lauderdale-fll",
    enabled: true,
  },
  {
    code: "GEG",
    name: "Spokane International Airport",
    city: "Spokane",
    state: "WA",
    timezone: "America/Los_Angeles",
    latitude: 47.587056,
    longitude: -117.5684754,
    slug: "spokane-geg",
    enabled: true,
  },
  {
    code: "GSO",
    name: "Piedmont Triad International Airport",
    city: "Greensboro",
    state: "NC",
    timezone: "America/New_York",
    latitude: 36.0829668,
    longitude: -79.9636208,
    slug: "greensboro-gso",
    enabled: true,
  },
  {
    code: "HOU",
    name: "William P. Hobby Airport",
    city: "Houston",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 29.659095,
    longitude: -95.2683903,
    slug: "houston-hou",
    enabled: true,
  },
  {
    code: "HPN",
    name: "Westchester County Airport",
    city: "White Plains",
    state: "NY",
    timezone: "America/New_York",
    latitude: 41.0490225,
    longitude: -73.7073449,
    slug: "white-plains-hpn",
    enabled: true,
  },
  {
    code: "IAD",
    name: "Washington Dulles International Airport",
    city: "Washington",
    state: "VA",
    timezone: "America/New_York",
    latitude: 38.9331752,
    longitude: -77.4274355,
    slug: "washington-iad",
    enabled: true,
  },
  {
    code: "IAH",
    name: "George Bush Intercontinental Airport",
    city: "Houston",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 29.9448817,
    longitude: -95.3325135,
    slug: "houston-iah",
    enabled: true,
  },
  {
    code: "IDA",
    name: "Idaho Falls Regional Airport",
    city: "Idaho Falls",
    state: "ID",
    timezone: "America/Boise",
    latitude: 43.4689933,
    longitude: -112.0877246,
    slug: "idaho-falls-ida",
    enabled: true,
  },
  {
    code: "IND",
    name: "Indianapolis International Airport",
    city: "Indianapolis",
    state: "IN",
    timezone: "America/Indiana/Indianapolis",
    latitude: 39.7293746,
    longitude: -86.2584777,
    slug: "indianapolis-ind",
    enabled: true,
  },
  {
    code: "JAX",
    name: "Jacksonville International Airport",
    city: "Jacksonville",
    state: "FL",
    timezone: "America/New_York",
    latitude: 30.4841701,
    longitude: -81.6557533,
    slug: "jacksonville-jax",
    enabled: true,
  },
  {
    code: "JFK",
    name: "John F. Kennedy International Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    latitude: 40.6676124,
    longitude: -73.7833159,
    slug: "new-york-jfk",
    enabled: true,
  },
  {
    code: "LAS",
    name: "Harry Reid International Airport",
    city: "Las Vegas",
    state: "NV",
    timezone: "America/Los_Angeles",
    latitude: 36.09981,
    longitude: -115.1486641,
    slug: "las-vegas-las",
    enabled: true,
  },
  {
    code: "LAX",
    name: "Los Angeles International Airport",
    city: "Los Angeles",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 33.9287349,
    longitude: -118.3959077,
    slug: "los-angeles-lax",
    enabled: true,
  },
  {
    code: "LGA",
    name: "LaGuardia Airport",
    city: "New York",
    state: "NY",
    timezone: "America/New_York",
    latitude: 40.7589732,
    longitude: -73.8323536,
    slug: "new-york-lga",
    enabled: true,
  },
  {
    code: "LIT",
    name: "Bill and Hillary Clinton National Airport",
    city: "Little Rock",
    state: "AR",
    timezone: "America/Chicago",
    latitude: 34.7142455,
    longitude: -92.2220101,
    slug: "little-rock-lit",
    enabled: true,
  },
  {
    code: "MCI",
    name: "Kansas City International Airport",
    city: "Kansas City",
    state: "MO",
    timezone: "America/Chicago",
    latitude: 39.269855,
    longitude: -94.668721,
    slug: "kansas-city-mci",
    enabled: true,
  },
  {
    code: "MCO",
    name: "Orlando International Airport",
    city: "Orlando",
    state: "FL",
    timezone: "America/New_York",
    latitude: 28.4608723,
    longitude: -81.2738138,
    slug: "orlando-mco",
    enabled: true,
  },
  {
    code: "MDW",
    name: "Chicago Midway International Airport",
    city: "Chicago",
    state: "IL",
    timezone: "America/Chicago",
    latitude: 41.8073232,
    longitude: -87.7460024,
    slug: "chicago-mdw",
    enabled: true,
  },
  {
    code: "MEM",
    name: "Memphis International Airport",
    city: "Memphis",
    state: "TN",
    timezone: "America/Chicago",
    latitude: 35.0755269,
    longitude: -89.9223107,
    slug: "memphis-mem",
    enabled: true,
  },
  {
    code: "MIA",
    name: "Miami International Airport",
    city: "Miami",
    state: "FL",
    timezone: "America/New_York",
    latitude: 25.8004501,
    longitude: -80.2631892,
    slug: "miami-mia",
    enabled: true,
  },
  {
    code: "MKE",
    name: "Milwaukee Mitchell International Airport",
    city: "Milwaukee",
    state: "WI",
    timezone: "America/Chicago",
    latitude: 42.9279249,
    longitude: -87.9324049,
    slug: "milwaukee-mke",
    enabled: true,
  },
  {
    code: "MLB",
    name: "Orlando Melbourne International Airport",
    city: "Melbourne",
    state: "FL",
    timezone: "America/New_York",
    latitude: 28.0901193,
    longitude: -80.6256264,
    slug: "melbourne-mlb",
    enabled: true,
  },
  {
    code: "MSP",
    name: "Minneapolis-Saint Paul International Airport",
    city: "Minneapolis",
    state: "MN",
    timezone: "America/Chicago",
    latitude: 44.8575957,
    longitude: -93.2262391,
    slug: "minneapolis-msp",
    enabled: true,
  },
  {
    code: "MSY",
    name: "Louis Armstrong New Orleans International Airport",
    city: "New Orleans",
    state: "LA",
    timezone: "America/Chicago",
    latitude: 30.0078303,
    longitude: -90.2505045,
    slug: "new-orleans-msy",
    enabled: true,
  },
  {
    code: "OAK",
    name: "Oakland International Airport",
    city: "Oakland",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 37.728199,
    longitude: -122.198206,
    slug: "oakland-oak",
    enabled: true,
  },
  {
    code: "OKC",
    name: "Will Rogers World Airport",
    city: "Oklahoma City",
    state: "OK",
    timezone: "America/Chicago",
    latitude: 35.443171,
    longitude: -97.602459,
    slug: "oklahoma-city-okc",
    enabled: true,
  },
  {
    code: "ORD",
    name: "O'Hare International Airport",
    city: "Chicago",
    state: "IL",
    timezone: "America/Chicago",
    latitude: 41.9514156,
    longitude: -87.8855614,
    slug: "chicago-ord",
    enabled: true,
  },
  {
    code: "ORF",
    name: "Norfolk International Airport",
    city: "Norfolk",
    state: "VA",
    timezone: "America/New_York",
    latitude: 36.8864096,
    longitude: -76.2179259,
    slug: "norfolk-orf",
    enabled: true,
  },
  {
    code: "PBI",
    name: "Palm Beach International Airport",
    city: "West Palm Beach",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.7075279,
    longitude: -80.0633705,
    slug: "west-palm-beach-pbi",
    enabled: true,
  },
  {
    code: "PDX",
    name: "Portland International Airport",
    city: "Portland",
    state: "OR",
    timezone: "America/Los_Angeles",
    latitude: 45.5732623,
    longitude: -122.5783862,
    slug: "portland-pdx",
    enabled: true,
  },
  {
    code: "PHL",
    name: "Philadelphia International Airport",
    city: "Philadelphia",
    state: "PA",
    timezone: "America/New_York",
    latitude: 39.8669666,
    longitude: -75.3099155,
    slug: "philadelphia-phl",
    enabled: true,
  },
  {
    code: "PHX",
    name: "Phoenix Sky Harbor International Airport",
    city: "Phoenix",
    state: "AZ",
    timezone: "America/Phoenix",
    latitude: 33.4488634,
    longitude: -111.9884391,
    slug: "phoenix-phx",
    enabled: true,
  },
  {
    code: "PIT",
    name: "Pittsburgh International Airport",
    city: "Pittsburgh",
    state: "PA",
    timezone: "America/New_York",
    latitude: 40.517654,
    longitude: -80.2678948,
    slug: "pittsburgh-pit",
    enabled: true,
  },
  {
    code: "POE",
    name: "Port Everglades Cruise Port",
    city: "Fort Lauderdale",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.1008389,
    longitude: -80.1136397,
    slug: "fort-lauderdale-poe",
    enabled: true,
  },
  {
    code: "PVD",
    name: "T.F. Green International Airport",
    city: "Providence",
    state: "RI",
    timezone: "America/New_York",
    latitude: 41.7253744,
    longitude: -71.4402359,
    slug: "providence-pvd",
    enabled: true,
  },
  {
    code: "RDU",
    name: "Raleigh-Durham International Airport",
    city: "Raleigh",
    state: "NC",
    timezone: "America/New_York",
    latitude: 35.8788879,
    longitude: -78.8390892,
    slug: "raleigh-rdu",
    enabled: true,
  },
  {
    code: "RIC",
    name: "Richmond International Airport",
    city: "Richmond",
    state: "VA",
    timezone: "America/New_York",
    latitude: 37.517275,
    longitude: -77.343479,
    slug: "richmond-ric",
    enabled: true,
  },
  {
    code: "RNO",
    name: "Reno-Tahoe International Airport",
    city: "Reno",
    state: "NV",
    timezone: "America/Los_Angeles",
    latitude: 39.533337,
    longitude: -119.7425587,
    slug: "reno-rno",
    enabled: true,
  },
  {
    code: "ROA",
    name: "Roanoke-Blacksburg Regional Airport",
    city: "Roanoke",
    state: "VA",
    timezone: "America/New_York",
    latitude: 37.3116218,
    longitude: -79.9743977,
    slug: "roanoke-roa",
    enabled: true,
  },
  {
    code: "ROC",
    name: "Greater Rochester International Airport",
    city: "Rochester",
    state: "NY",
    timezone: "America/New_York",
    latitude: 43.1380517,
    longitude: -77.6687792,
    slug: "rochester-roc",
    enabled: true,
  },
  {
    code: "RSW",
    name: "Southwest Florida International Airport",
    city: "Fort Myers",
    state: "FL",
    timezone: "America/New_York",
    latitude: 26.5074637,
    longitude: -81.7833478,
    slug: "fort-myers-rsw",
    enabled: true,
  },
  {
    code: "SAN",
    name: "San Diego International Airport",
    city: "San Diego",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 32.7373579,
    longitude: -117.1792751,
    slug: "san-diego-san",
    enabled: true,
  },
  {
    code: "SAT",
    name: "San Antonio International Airport",
    city: "San Antonio",
    state: "TX",
    timezone: "America/Chicago",
    latitude: 29.5188305,
    longitude: -98.4639703,
    slug: "san-antonio-sat",
    enabled: true,
  },
  {
    code: "SAV",
    name: "Savannah/Hilton Head International Airport",
    city: "Savannah",
    state: "GA",
    timezone: "America/New_York",
    latitude: 32.1383925,
    longitude: -81.242547,
    slug: "savannah-sav",
    enabled: true,
  },
  {
    code: "SDF",
    name: "Louisville Muhammad Ali International Airport",
    city: "Louisville",
    state: "KY",
    timezone: "America/New_York",
    latitude: 38.1902131,
    longitude: -85.7443519,
    slug: "louisville-sdf",
    enabled: true,
  },
  {
    code: "SEA",
    name: "Seattle-Tacoma International Airport",
    city: "Seattle",
    state: "WA",
    timezone: "America/Los_Angeles",
    latitude: 47.4785672,
    longitude: -122.2835232,
    slug: "seattle-sea",
    enabled: true,
  },
  {
    code: "SFO",
    name: "San Francisco International Airport",
    city: "San Francisco",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 37.6729598,
    longitude: -122.388382,
    slug: "san-francisco-sfo",
    enabled: true,
  },
  {
    code: "SJC",
    name: "San Jose Mineta International Airport",
    city: "San Jose",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 37.3672863,
    longitude: -121.9084771,
    slug: "san-jose-sjc",
    enabled: true,
  },
  {
    code: "SLC",
    name: "Salt Lake City International Airport",
    city: "Salt Lake City",
    state: "UT",
    timezone: "America/Denver",
    latitude: 40.7703143,
    longitude: -111.9384158,
    slug: "salt-lake-city-slc",
    enabled: true,
  },
  {
    code: "SNA",
    name: "John Wayne Airport",
    city: "Santa Ana",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 33.7004604,
    longitude: -117.8662159,
    slug: "santa-ana-sna",
    enabled: true,
  },
  {
    code: "STL",
    name: "St. Louis Lambert International Airport",
    city: "St. Louis",
    state: "MO",
    timezone: "America/Chicago",
    latitude: 38.7353742,
    longitude: -90.3575518,
    slug: "st-louis-stl",
    enabled: true,
  },
  {
    code: "SYR",
    name: "Syracuse Hancock International Airport",
    city: "Syracuse",
    state: "NY",
    timezone: "America/New_York",
    latitude: 43.0922635,
    longitude: -76.0853629,
    slug: "syracuse-syr",
    enabled: true,
  },
  {
    code: "TPA",
    name: "Tampa International Airport",
    city: "Tampa",
    state: "FL",
    timezone: "America/New_York",
    latitude: 27.9670153,
    longitude: -82.5703222,
    slug: "tampa-tpa",
    enabled: true,
  },
  {
    code: "TUS",
    name: "Tucson International Airport",
    city: "Tucson",
    state: "AZ",
    timezone: "America/Phoenix",
    latitude: 32.1237838,
    longitude: -110.9359942,
    slug: "tucson-tus",
    enabled: true,
  },
  {
    code: "TYS",
    name: "McGhee Tyson Airport",
    city: "Knoxville",
    state: "TN",
    timezone: "America/New_York",
    latitude: 35.8232586,
    longitude: -83.976024,
    slug: "knoxville-tys",
    enabled: true,
  },
  {
    code: "YOW",
    name: "Ottawa Macdonald-Cartier International Airport",
    city: "Ottawa",
    state: "ON",
    country: "Canada",
    timezone: "America/Toronto",
    latitude: 45.3194963,
    longitude: -75.6242593,
    slug: "ottawa-yow",
    enabled: true,
  },
  {
    code: "YUL",
    name: "Montreal-Pierre Elliott Trudeau International Airport",
    city: "Montreal",
    state: "QC",
    country: "Canada",
    timezone: "America/Toronto",
    latitude: 45.4856182,
    longitude: -73.6971636,
    slug: "montreal-yul",
    enabled: true,
  },
  {
    code: "YYC",
    name: "Calgary International Airport",
    city: "Calgary",
    state: "AB",
    country: "Canada",
    timezone: "America/Edmonton",
    latitude: 51.0938182,
    longitude: -114.004205,
    slug: "calgary-yyc",
    enabled: true,
  },
  {
    code: "YYZ",
    name: "Toronto Pearson International Airport",
    city: "Toronto",
    state: "ON",
    country: "Canada",
    timezone: "America/Toronto",
    latitude: 43.6933935,
    longitude: -79.6277555,
    slug: "toronto-yyz",
    enabled: true,
  },

  // ==========================================================================
  // Test Locations (ResLab Sandbox) — DISABLED for production
  // ==========================================================================
  {
    code: "TEST-NY",
    name: "Beacon Test Airport (TEST)",
    city: "Beacon",
    state: "NY",
    timezone: "America/New_York",
    latitude: 41.5048158,
    longitude: -73.9695832,
    slug: "beacon-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 195,
  },
  {
    code: "TEST-OH",
    name: "Cincinnati Test Airport (TEST)",
    city: "Cincinnati",
    state: "OH",
    timezone: "America/New_York",
    latitude: 39.1031182,
    longitude: -84.5120196,
    slug: "cincinnati-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 194,
  },
  {
    code: "TEST-CA",
    name: "Albany CA Test Airport (TEST)",
    city: "Albany",
    state: "CA",
    timezone: "America/Los_Angeles",
    latitude: 35.125801,
    longitude: -117.9859038,
    slug: "albany-ca-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 197,
  },
  {
    code: "TEST-QC",
    name: "Montreal Test Airport (TEST)",
    city: "Montreal",
    state: "QC",
    country: "Canada",
    timezone: "America/New_York",
    latitude: 45.5016889,
    longitude: -73.567256,
    slug: "montreal-test",
    enabled: false,
    isTest: true,
    reslabLocationId: 196,
  },
];

export const airportsByCode = airports.reduce(
  (acc, airport) => {
    acc[airport.code] = airport;
    return acc;
  },
  {} as Record<string, Airport>
);

export const airportsBySlug = airports.reduce(
  (acc, airport) => {
    acc[airport.slug] = airport;
    return acc;
  },
  {} as Record<string, Airport>
);

export const enabledAirports = airports.filter((a) => a.enabled);

// Production airports only (excludes test locations)
export const productionAirports = airports.filter(
  (a) => a.enabled && !a.isTest
);

// Test airports only
export const testAirports = airports.filter((a) => a.enabled && a.isTest);

export function getAirportByCode(code: string): Airport | undefined {
  return airportsByCode[code.toUpperCase()];
}

export function getAirportBySlug(slug: string): Airport | undefined {
  return airportsBySlug[slug.toLowerCase()];
}

export function getAirportByReslabLocationId(
  locationId: number
): Airport | undefined {
  return airports.find((a) => a.reslabLocationId === locationId);
}
